spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/friendmall_ums?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver # 有待商榷
  # 每个微服务想要在注册中心中配置，需要指定注册中心的地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: friendmall-member
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: 192.168.56.10
    port: 6379
  #    zipkin 可视化链路追踪
  zipkin:
    base-url: "http://192.168.56.10:9411/"
    discovery-client-enabled: false  # 关闭自己的服务发现功能，不要被 Spring Cloud 发现
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1  # 数据采样率

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8060

