spring:
  application:
    name: friendmall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #    zipkin 可视化链路追踪
  zipkin:
    base-url: "http://192.168.56.10:9411/"
    discovery-client-enabled: false  # 关闭自己的服务发现功能，不要被 Spring Cloud 发现
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1  # 数据采样率

server:
  port: 20000
#logging:
#  level:
#    com.aeterna.friendmall: debug
alibaba:
  cloud:
    access-key:
    secret-key:
    oss:
      endpoint:
      bucket: friendmall
    sms:
      host:
      path: /sms/smsSend
      appcode:
      smsSignId:
      templateId:

